apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./k8s/infra/external-secrets/external-secrets
      sourceRef:
        kind: GitRepository
        name: homelab
        namespace: flux-system
  releaseName: external-secrets
  targetNamespace: external-secrets
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  dependsOn:
    - name: base
      namespace: flux-system
    - name: istiod
      namespace: flux-system
    - name: cni
      namespace: flux-system
    - name: ztunnel
      namespace: flux-system
  values:
    external-secrets:
      bitwarden-sdk-server:
        enabled: true
      namespaceOverride: "external-secrets"
      image:
        tls:
          enabled: true
          volumeMounts:
            - mountPath: "/certs"
              name: "bitwarden-tls-certs"
          volumes:
            - name: "bitwarden-tls-certs"
              secret:
                secretName: "bitwarden-tls-certs"
                items:
                  - key: "tls.crt"
                    path: "cert.pem"
                  - key: "tls.key"
                    path: "key.pem"
                  - key: "ca.crt"
                    path: "ca.pem"
