apiVersion: v2
name: actual
description: "Actual Budget deployment for homelab"
type: application
version: 0.1.0
dependencies:
  - name: home-ops-chart
    version: 0.2.0
    repository: oci://zot.schober.dev/helm
