image:
  repository: lscr.io/linuxserver/prowlarr
  tag: "1.32.2"
  pullPolicy: IfNotPresent

env:
  PUID: "1000"
  PGID: "1000"
  TZ: Europe/Vienna

proxy:
  HTTP_PROXY: "http://gluetun-proxy.media.svc.cluster.local:8888"
  HTTPS_PROXY: "http://gluetun-proxy.media.svc.cluster.local:8888"
  NO_PROXY: "localhost,127.0.0.1,.svc.cluster.local,.cluster.local"

service:
  port: 80
  targetPort: 9696

persistence:
  config:
    enabled: true
    create: true
    claimName: prowlarr-config
    size: 2Gi
    mountPath: /config

app:
  host: prowlarr.schober.dev
  gateway:
    name: internal-gateway
    namespace: istio-ingress-internal
    sectionName: https
  backendServiceName: prowlarr
  servicePort: 80
  authentik:
    enabled: true
    provider: authentik
    outpostService:
      name: ak-outpost-proxy
      namespace: authentik
      port: 9000
