apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault-config-operator
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./k8s/infra/vault-config-operator/vault-config-operator
  prune: true
  dependsOn:
    - name: namespaces
    # webhook serving cert (selfsigned Issuer + Certificate, cainjector)
    - name: cert-manager
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: vault-config-operator
      namespace: flux-system
