apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-grafana-backup-credentials
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: bitwarden-app-secrets
    kind: ClusterSecretStore
  target:
    name: cnpg-grafana-backup-credentials
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .versitygw_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .versitygw_secret_access_key }}"
  data:
    - secretKey: versitygw_access_key_id
      remoteRef:
        key: versitygw-access-key-id
    - secretKey: versitygw_secret_access_key
      remoteRef:
        key: versitygw-secret-access-key
