apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: grafana-postgres
  namespace: {{ .Release.Namespace }}
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: longhorn-static
      volumeName: longhorn-grafana-postgres
  bootstrap:
    initdb:
      database: grafana
      owner: grafana
