apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: grafana-postgres
  namespace: {{ .Release.Namespace }}
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: local-path
  managed:
    roles:
      - name: grafana
        ensure: present
        login: true
        passwordSecret:
          name: cnpg-grafana-credentials
  bootstrap:
    initdb:
      database: grafana
      owner: grafana
  backup:
    retentionPolicy: "30d"
    barmanObjectStore:
      destinationPath: "s3://cnpg-backups/grafana/"
      endpointURL: "https://s3.versitygw.schober.dev"
      s3Credentials:
        accessKeyId:
          name: cnpg-grafana-backup-credentials
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-grafana-backup-credentials
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: "gzip"
        maxParallel: 8
