apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: grafana-versitygw-store
  namespace: {{ .Release.Namespace }}
spec:
  instanceSidecarConfiguration:
    env:
      - name: AWS_DEFAULT_REGION
        value: homelab
  configuration:
    destinationPath: s3://cnpg-backups/grafana/
    endpointURL: http://versitygw.versitygw.svc.cluster.local:7070
    s3Credentials:
      accessKeyId:
        name: cnpg-grafana-backup-credentials
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: cnpg-grafana-backup-credentials
        key: AWS_SECRET_ACCESS_KEY
    wal:
      compression: gzip
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: backup-grafana-postgres
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "10 15 * * *"
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: grafana-versitygw-store
  cluster:
    name: grafana-postgres
