image:
  repository: lscr.io/linuxserver/sonarr
  tag: "4.0.18"
  pullPolicy: IfNotPresent

env:
  PUID: "1000"
  PGID: "1000"
  TZ: Europe/Vienna

proxy:
  HTTP_PROXY: "http://gluetun-proxy.media.svc.cluster.local:8888"
  HTTPS_PROXY: "http://gluetun-proxy.media.svc.cluster.local:8888"
  NO_PROXY: "localhost,127.0.0.1,.svc.cluster.local,.cluster.local"

service:
  port: 80
  targetPort: 8989

persistence:
  config:
    enabled: true
    create: true
    claimName: sonarr-config
    size: 5Gi
    mountPath: /config
    storageClass: truenas-iscsi-db
  media:
    enabled: true
    create: false
    claimName: media-library
    mountPath: /media
    storageClass: truenas-nfs-media
  downloads:
    enabled: true
    create: false
    claimName: media-downloads
    mountPath: /downloads
    storageClass: truenas-nfs-media

app:
  host: sonarr.schober.dev
  gateway:
    name: internal-gateway
    namespace: istio-ingress-internal
    sectionName: https
  backendServiceName: sonarr
  servicePort: 80
  authentik:
    enabled: true
    provider: authentik
    outpostService:
      name: ak-outpost-proxy
      namespace: authentik
      port: 9000

externalSecret:
  enabled: true
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-app-secrets
    kind: ClusterSecretStore
  keys:
    apiKey: sonarr-api-key
