apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 10m
  url: https://istio-release.storage.googleapis.com/charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  type: oci
  interval: 10m
  url: oci://quay.io/jetstack/charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: intel
  namespace: flux-system
spec:
  interval: 10m
  url: https://intel.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: headlamp-repo
  namespace: flux-system
spec:
  interval: 10m
  url: https://kubernetes-sigs.github.io/headlamp/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: local-path-provisioner-repo
  namespace: flux-system
spec:
  type: oci
  interval: 10m
  url: oci://ghcr.io/rancher/local-path-provisioner/charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: volsync-repo
  namespace: flux-system
spec:
  interval: 10m
  url: https://backube.github.io/helm-charts/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudnative-pg-repo
  namespace: flux-system
spec:
  interval: 10m
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: snapshot-controller-repo
  namespace: flux-system
spec:
  interval: 10m
  url: https://democratic-csi.github.io/charts/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: argo-cd-repo
  namespace: flux-system
spec:
  interval: 10m
  url: https://argoproj.github.io/argo-helm
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: node-feature-discovery-repo
  namespace: flux-system
spec:
  interval: 10m
  url: https://kubernetes-sigs.github.io/node-feature-discovery/charts

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: controlplaneio-fluxcd
  namespace: flux-system
spec:
  type: oci
  interval: 10m
  url: oci://ghcr.io/controlplaneio-fluxcd/charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: stakater-repo
  namespace: flux-system
spec:
  interval: 10m
  url: https://stakater.github.io/stakater-charts