apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repositories.yaml
  - argocd
  - authentik
  - cert-manager
  - cnpg
  - default
  - democratic-csi
  - external-dns
  - external-secrets
  - intel
  - istio-ingress-internal
  - istio-system
  - kube-system
  - monitoring
  - node-feature-discovery
  - rancher
  - valkey
  - versitygw
  - volsync-system
