apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
{{- include "versitygw.labels" . | nindent 4 }}
  name: versitygw-admin
  namespace: {{ .Release.Namespace }}
spec:
  hostnames:
    - admin.versitygw.schober.dev
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: internal-gateway
      namespace: istio-ingress-internal
      sectionName: versitygw-https
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: versitygw
          port: 7071
          weight: 1
      filters:
        - cors:
            allowOrigins:
              - https://web.versitygw.schober.dev
            allowCredentials: true
            type: CORS
      matches:
        - path:
            type: PathPrefix
            value: /