{{- range .Values.dataClients }}
{{- $client := . }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $client.name }}-versitygw-generated
  namespace: {{ $.Release.Namespace }}
spec:
  refreshPolicy: CreatedOnce
  target:
    name: {{ $client.name }}-versitygw-generated
    template:
      engineVersion: v2
      data:
        accessKeyId: "{{ $client.name }}"
        secretAccessKey: "{{ `{{ .password }}` }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: versitygw-client-secret
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ $client.name }}-versitygw-push
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: 1h
  deletionPolicy: None
  updatePolicy: Replace
  secretStoreRefs:
    - name: bitwarden-app-secrets
      kind: ClusterSecretStore
  selector:
    secret:
      name: {{ $client.name }}-versitygw-generated
  data:
    - match:
        secretKey: accessKeyId
        remoteRef:
          remoteKey: {{ $client.name }}-id
    - match:
        secretKey: secretAccessKey
        remoteRef:
          remoteKey: {{ $client.name }}-secret
---
{{- end }}
