apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: versitygw-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: bitwarden-app-secrets
    kind: ClusterSecretStore
  target:
    name: versitygw-credentials
  data:
    - secretKey: rootAccessKeyId
      remoteRef:
        key: versitygw-access-key-id
    - secretKey: rootSecretAccessKey
      remoteRef:
        key: versitygw-secret-access-key
