apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-zot-oci-repository
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: argocd-zot-oci-repository
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
          argocd.argoproj.io/secret-type: repository
      data:
        name: zot-oci-helm
        type: helm
        url: zot.schober.dev/helm
        enableOCI: "true"
        username: "{{`{{ .username }}`}}"
        password: "{{`{{ .password }}`}}"
  data:
    - secretKey: username
      remoteRef:
        key: argocd-zot-repo-username
    - secretKey: password
      remoteRef:
        key: argocd-zot-repo-password
