apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: seerr-db-password
  namespace: {{ .Release.Namespace }}
spec:
  length: 42
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr-db-generated
  namespace: {{ .Release.Namespace }}
spec:
  refreshPolicy: CreatedOnce
  target:
    name: seerr-db-generated
    template:
      engineVersion: v2
      data:
        password: "{{ `{{ .password }}` }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: seerr-db-password
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: seerr-db-push
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  deletionPolicy: None
  updatePolicy: IfNotExists
  secretStoreRefs:
    - name: bitwarden-cnpg-secrets
      kind: ClusterSecretStore
  selector:
    secret:
      name: seerr-db-generated
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: {{ .Values.externalSecret.cnpgPasswordKey | quote }}
