apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valkey-data-valkey-primary
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-csi
  volumeName: pv-valkey
  resources:
    requests:
      storage: 2Gi
