apiVersion: v1
kind: ConfigMap
metadata:
  name: configarr-config
  namespace: {{ .Release.Namespace }}
data:
  config.yml: |
    sonarr:
      instance1:
        base_url: {{ .Values.config.sonarr.baseUrl | quote }}
        api_key: !env SONARR_API_KEY
        download_clients:
          data:
            - name: {{ .Values.config.sonarr.downloadClientName | quote }}
              type: qbittorrent
              enable: true
              priority: 1
              remove_completed_downloads: false
              remove_failed_downloads: false
              fields:
                host: {{ .Values.config.qbittorrent.host | quote }}
                port: {{ .Values.config.qbittorrent.port }}
                use_ssl: {{ .Values.config.qbittorrent.useSsl }}
                url_base: {{ .Values.config.qbittorrent.urlBase | quote }}
                api_key: !env QBITTORRENT_API_KEY
                tv_category: {{ .Values.config.sonarr.category | quote }}
          update_password: true
          delete_unmanaged:
            enabled: false
    radarr:
      instance1:
        base_url: {{ .Values.config.radarr.baseUrl | quote }}
        api_key: !env RADARR_API_KEY
        download_clients:
          data:
            - name: {{ .Values.config.radarr.downloadClientName | quote }}
              type: qbittorrent
              enable: true
              priority: 1
              remove_completed_downloads: false
              remove_failed_downloads: false
              fields:
                host: {{ .Values.config.qbittorrent.host | quote }}
                port: {{ .Values.config.qbittorrent.port }}
                use_ssl: {{ .Values.config.qbittorrent.useSsl }}
                url_base: {{ .Values.config.qbittorrent.urlBase | quote }}
                api_key: !env QBITTORRENT_API_KEY
                movie_category: {{ .Values.config.radarr.category | quote }}
          update_password: true
          delete_unmanaged:
            enabled: false
