{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: configarr-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: configarr-secret
  data:
    - secretKey: SONARR_API_KEY
      remoteRef:
        key: {{ .Values.externalSecret.keys.sonarrApiKey | quote }}
    - secretKey: RADARR_API_KEY
      remoteRef:
        key: {{ .Values.externalSecret.keys.radarrApiKey | quote }}
    - secretKey: QBITTORRENT_API_KEY
      remoteRef:
        key: {{ .Values.externalSecret.keys.qbittorrentApiKey | quote }}
{{- end }}
