{{- if and .Values.ldapAuth.enabled .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyfin-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: jellyfin-secret
  data:
    - secretKey: ldapBindPassword
      remoteRef:
        key: {{ .Values.externalSecret.keys.ldapBindPassword | quote }}
{{- end }}
