apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../cnpg
  - ../external-dns
  - ../istio-ingress-internal
  - ../valkey
  - ../versitygw
  - ../intel
  - ../node-feature-discovery
  - ../kube-system/headlamp
