apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: radarr-versitygw-store
  namespace: {{ .Release.Namespace }}
spec:
  configuration:
    destinationPath: s3://cnpg-backups/radarr/
    endpointURL: http://versitygw.versitygw.svc.cluster.local:7070
    s3Credentials:
      accessKeyId:
        name: cnpg-radarr-backup-credentials
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: cnpg-radarr-backup-credentials
        key: AWS_SECRET_ACCESS_KEY
    wal:
      compression: gzip
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: backup-{{ .Values.postgres.clusterName }}
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "40 15 * * *"
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: radarr-versitygw-store
  cluster:
    name: {{ .Values.postgres.clusterName }}
