apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.claimName }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.accessMode }}
  resources:
    requests:
      storage: {{ .Values.size }}
  storageClassName: {{ .Values.storageClass }}
