apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-proxmox
  namespace: {{ .Release.Namespace }}
spec:
  hostnames:
    - {{ .Values.proxmox.host }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
      sectionName: {{ .Values.gateway.sectionName }}
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: proxmox
          port: {{ .Values.proxmox.port }}
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
