apiVersion: v1
kind: Service
metadata:
  name: proxmox
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: https
      port: {{ .Values.proxmox.port }}
      targetPort: {{ .Values.proxmox.port }}
      protocol: TCP
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: proxmox
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - proxmox.{{ .Release.Namespace }}.svc.cluster.local
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: {{ .Values.proxmox.port }}
      protocol: TLS
  resolution: STATIC
  endpoints:
    - address: {{ .Values.proxmox.ip }}
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: proxmox
  namespace: {{ .Release.Namespace }}
spec:
  host: proxmox.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: SIMPLE
