apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-csi
  volumeName: pv-n8n
  resources:
    requests:
      storage: 5Gi
