apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.pvc.storageClass }}
  {{- with .Values.pvc.volumeName }}
  volumeName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
