{{- if not .Values.staging.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-letsencrypt
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    profile: tlsserver
    privateKeySecretRef:
      name: cloudflare-acme-prod
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
          cnameStrategy: Follow
{{- end }}
{{- if .Values.staging.enabled }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-letsencrypt-staging
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    profile: tlsserver
    privateKeySecretRef:
      name: cloudflare-acme-staging
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
          cnameStrategy: Follow
{{- end }}