image:
  repository: jellyfin/jellyfin
  tag: "10.11.6"
  pullPolicy: IfNotPresent

env:
  JELLYFIN_PublishedServerUrl: https://jellyfin.schober.dev

ldapAuth:
  enabled: true
  server: ak-outpost-jellyfin-ldap.authentik.svc.cluster.local
  port: 389
  useSsl: false
  useStartTls: false
  skipSslVerify: false
  bindUser: cn=jellyfin-ldap,ou=users,dc=ldap,dc=schober,dc=dev
  baseDn: dc=ldap,dc=schober,dc=dev
  searchFilter: (|(memberOf=cn=jellyfin-users,ou=groups,dc=ldap,dc=schober,dc=dev)(memberOf=cn=jellyfin-admins,ou=groups,dc=ldap,dc=schober,dc=dev))
  adminBaseDn: ou=users,dc=ldap,dc=schober,dc=dev
  adminFilter: (memberOf=cn=jellyfin-admins,ou=groups,dc=ldap,dc=schober,dc=dev)
  enableAdminFilterMemberUid: false
  searchAttributes: cn,mail
  clientCertPath: ""
  clientKeyPath: ""
  rootCaPath: ""
  createUsersFromLdap: true
  allowPassChange: false
  uidAttribute: uid
  usernameAttribute: cn
  passwordAttribute: userPassword
  enableProfileImageSync: false
  removeImagesNotInLdap: false
  profileImageAttribute: jpegphoto
  profileImageFormat: Default
  enableAllFolders: false
  passwordResetUrl: ""

service:
  port: 80
  targetPort: 8096

persistence:
  config:
    enabled: true
    create: true
    claimName: jellyfin-config
    size: 10Gi
    mountPath: /config
    storageClass: truenas-iscsi-db
  media:
    enabled: true
    create: false
    claimName: media-library
    mountPath: /media
    readOnly: true
    storageClass: truenas-nfs-media

app:
  host: jellyfin.schober.dev
  gateway:
    name: internal-gateway
    namespace: istio-ingress-internal
    sectionName: https
  backendServiceName: jellyfin
  servicePort: 80
  authentik:
    enabled: false
    provider: authentik

externalSecret:
  enabled: true
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-app-secrets
    kind: ClusterSecretStore
  keys:
    ldapBindPassword: authentik-user-jellyfin-ldap-password
