image:
  repository: fallenbagel/jellyseerr
  tag: "2.3.0"
  pullPolicy: IfNotPresent

env:
  TZ: Europe/Vienna

service:
  port: 80
  targetPort: 5055

persistence:
  config:
    enabled: true
    claimName: jellyseerr-config
    size: 2Gi
    mountPath: /app/config

app:
  host: seerr.schober.dev
  gateway:
    name: internal-gateway
    namespace: istio-ingress-internal
    sectionName: https
  backendServiceName: jellyseerr
  servicePort: 80
  authentik:
    enabled: true
    provider: authentik
