apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-gluetun
  namespace: {{ .Release.Namespace }}
  labels:
    app: qbittorrent
data:
  {{- range $key, $value := .Values.gluetun.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
