{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gluetun-vpn-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: gluetun-vpn-secret
  data:
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: {{ .Values.externalSecret.keys.wireguardPrivateKey | quote }}
{{- if .Values.qbittorrent.apiKey.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.qbittorrent.apiKey.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.qbittorrent.apiKey.secretName }}
  data:
    - secretKey: {{ .Values.qbittorrent.apiKey.secretKey }}
      remoteRef:
        key: {{ .Values.externalSecret.keys.qbittorrentApiKey | quote }}
{{- end }}
{{- end }}
