apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.backendServiceName }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: qbittorrent
  ports:
    - name: http
      port: {{ .Values.qbittorrent.service.port }}
      targetPort: {{ .Values.qbittorrent.service.targetPort }}
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: gluetun-proxy
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: qbittorrent
  ports:
    - name: http-proxy
      port: {{ .Values.proxy.service.port }}
      targetPort: 8888
      protocol: TCP
