truenas:
  host: truenas.schober.dev
  port: 443
  allowInsecure: false
  datasetParentName: hdd/k8s/b/v
  detachedSnapshotsDatasetParentName: hdd/k8s/b/s

  targetPortal: "truenas.schober.dev:3260"
  targetGroupPortalGroup: 1
  targetGroupInitiatorGroup: 1

democratic-csi:
  csiDriver:
    name: org.democratic-csi.iscsi

  driver:
    existingConfigSecret: truenas-iscsi-config
    config:
      driver: freenas-api-iscsi

  storageClasses:
    - name: truenas-iscsi-db
      defaultClass: false
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: xfs
        namePrefix: iscsi-db-
        config: |
          zfs:
            zvolBlocksize: "16K"

    - name: truenas-iscsi-object
      defaultClass: false
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: xfs
        namePrefix: iscsi-object-
        config: |
          zfs:
            zvolBlocksize: "128K"

  volumeSnapshotClasses:
    - name: truenas-iscsi
      deletionPolicy: Retain
      parameters:
        detachedSnapshots: "true"

  controller:
    externalSnapshotter:
      enabled: true
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
    driver:
      image:
        tag: v1.9.5

  node:
    hostPID: true
    driver:
      extraEnv:
        - name: ISCSIADM_HOST_STRATEGY
          value: nsenter
        - name: ISCSIADM_HOST_PATH
          value: /usr/local/sbin/iscsiadm
      iscsiDirHostPath: /var/iscsi
      iscsiDirHostPathType: ""
      image:
        tag: v1.9.5
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
