apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: truenas-nfs-config
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-app-secrets
    kind: ClusterSecretStore
  target:
    name: truenas-nfs-config
    template:
      data:
        driver-config-file.yaml: |
          driver: freenas-api-nfs
          httpConnection:
            protocol: https
            host: {{ .Values.truenas.host }}
            port: {{ .Values.truenas.port }}
            apiKey: "{{ `{{ .apiKey }}` }}"
            allowInsecure: {{ .Values.truenas.allowInsecure }}
            apiVersion: 2
          zfs:
            datasetParentName: {{ .Values.truenas.datasetParentName }}
            detachedSnapshotsDatasetParentName: {{ .Values.truenas.detachedSnapshotsDatasetParentName }}
            zvolCompression: lz4
            zvolDedup: "off"
            zvolEnableReservation: false
            datasetPermissionsMode: "0777"
            datasetPermissionsUser: 0
            datasetPermissionsGroup: 0
            datasetEnableQuotas: true
            datasetEnableReservation: false
          nfs:
            shareHost: "{{ .Values.truenas.host }}"
            shareMaprootUser: root
            shareMaprootGroup: wheel
  data:
    - secretKey: apiKey
      remoteRef:
        key: truenas-api-key