apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-authentik-oidc
  namespace: flux-system
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-app-secrets
    kind: ClusterSecretStore
  target:
    name: flux-authentik-oidc
  data:
    - secretKey: client-secret
      remoteRef:
        key: authentik-flux-client-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-web-homelab-admins
subjects:
  - kind: Group
    name: homelab-admins
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: flux-web-admin
  apiGroup: rbac.authorization.k8s.io
