{{- $app := default dict .Values.app -}}
{{- $authentik := default dict (get $app "authentik") -}}
{{- if and (get $authentik "enabled") (get $app "host") }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: adguard-authz
  namespace: {{ default "istio-ingress-internal" (get (default dict (get $app "gateway")) "namespace") }}
spec:
  targetRef:
    kind: Gateway
    group: gateway.networking.k8s.io
    name: {{ default "internal-gateway" (get (default dict (get $app "gateway")) "name") }}
  action: CUSTOM
  provider:
    name: {{ default "authentik" (get $authentik "provider") }}
  rules:
    - to:
        - operation:
            hosts:
              - {{ get $app "host" }}
{{- end }}
