{{- $pvc := default dict .Values.pvc -}}
{{- if (default false (get $pvc "enabled")) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ default "adguard-data" (get $pvc "claimName") }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ default "proxmox-csi" (get $pvc "storageClass") }}
  volumeName: {{ default "pv-adguard" (get $pvc "volumeName") }}
  resources:
    requests:
      storage: {{ default "2Gi" (get $pvc "size") }}
{{- end }}
