{{- $svc := default dict .Values.service -}}
{{- $web := default dict (get $svc "web") -}}
apiVersion: v1
kind: Service
metadata:
  name: adguard-web
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: adguard
  ports:
    - name: http
      port: {{ default 80 (get $web "port") }}
      targetPort: {{ default 3000 (get $web "targetPort") }}
      protocol: TCP
