apiVersion: v2
name: valkey
description: "Valkey deployment for homelab"
type: application
version: 0.1.0
dependencies:
  - name: valkey
    version: 0.11.0
    repository: https://valkey.io/valkey-helm
