apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: truenas-iscsi-config
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-app-secrets
    kind: ClusterSecretStore
  target:
    name: truenas-iscsi-config
    template:
      data:
        driver-config-file.yaml: |
          driver: freenas-api-iscsi
          httpConnection:
            protocol: https
            host: {{ .Values.truenas.host }}
            port: {{ .Values.truenas.port }}
            apiKey: "{{ `{{ .apiKey }}` }}"
            allowInsecure: {{ .Values.truenas.allowInsecure }}
            apiVersion: 2
          zfs:
            datasetParentName: {{ .Values.truenas.datasetParentName }}
            detachedSnapshotsDatasetParentName: {{ .Values.truenas.detachedSnapshotsDatasetParentName }}
            zvolCompression: lz4
            zvolEnableReservation: false
          iscsi:
            targetPortal: "{{ .Values.truenas.targetPortal }}"
            nameTemplate: "{{ .pvc.metadata.name }}-{{ .pvc.metadata.uid | trunc 6 }}"
            targetGroups:
              - targetGroupPortalGroup: {{ .Values.truenas.targetGroupPortalGroup }}
                targetGroupInitiatorGroup: {{ .Values.truenas.targetGroupInitiatorGroup }}
                targetGroupAuthType: None
            extentInsecureTpc: true
            extentXenCompat: false
            extentDisablePhysicalBlocksize: true
            extentBlocksize: 4096
            extentAvailThreshold: 0
  data:
    - secretKey: apiKey
      remoteRef:
        key: truenas-api-key
