apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: {{ .Release.Namespace }}
  labels:
    app: prowlarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PUID
              value: {{ .Values.env.PUID | quote }}
            - name: PGID
              value: {{ .Values.env.PGID | quote }}
            - name: TZ
              value: {{ .Values.env.TZ | quote }}
            {{- if .Values.proxy }}
            - name: HTTP_PROXY
              value: {{ .Values.proxy.HTTP_PROXY | quote }}
            - name: HTTPS_PROXY
              value: {{ .Values.proxy.HTTPS_PROXY | quote }}
            - name: NO_PROXY
              value: {{ .Values.proxy.NO_PROXY | quote }}
            - name: http_proxy
              value: {{ .Values.proxy.HTTP_PROXY | quote }}
            - name: https_proxy
              value: {{ .Values.proxy.HTTPS_PROXY | quote }}
            - name: no_proxy
              value: {{ .Values.proxy.NO_PROXY | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            {{- if .Values.persistence.config.enabled }}
            - name: config
              mountPath: {{ .Values.persistence.config.mountPath }}
            {{- end }}
      volumes:
        {{- if .Values.persistence.config.enabled }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.config.claimName }}
        {{- end }}
