# Physical host: panoptes
apiVersion: v1alpha1
kind: UnattendedInstallConfig
provisioning:
  diskSelector:
    match: disk.dev_path == "/dev/nvme0n1"
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: ctrl-02
---
apiVersion: v1alpha1
kind: KubeNodeConfig
labels:
  topology.kubernetes.io/zone: panoptes
---
apiVersion: v1alpha1
kind: LinkConfig
name: eno2
addresses:
  - address: 10.1.40.12/24
routes:
  - gateway: 10.1.40.1
---
apiVersion: v1alpha1
kind: Layer2VIPConfig
name: 10.1.40.10
link: eno2
