apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gateway
  namespace: flux-system
spec:
  interval: 5m
  timeout: 5m
  chart:
    spec:
      chart: ./k8s/infra/istio-ingress-internal/gateway
      sourceRef:
        kind: GitRepository
        name: homelab
        namespace: flux-system
      reconcileStrategy: Revision
  releaseName: gateway
  targetNamespace: istio-ingress-internal
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  values:

